[package]
name = "yew-app"
version = "0.1.0"
authors = ["Diego Pacheco <diego.pacheco.it@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = "0.11.0"
