[package]
name = "main"
version = "1.0.0"
authors = ["Diego.Pacheco"]
edition = "2018"

[dependencies]
surf = "1.0.3"
async-std = { version = "1.4.0", features = ["default","attributes","std","unstable"] }
serde_json = "1.0.44"
