[package]
name = "snake_game"
version = "0.1.0"
authors = ["Douglas Alves <douglas.alves@blu365.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
piston_window = "0.117.0"